using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphProject
{
    /// <summary>
    /// This enum contains all the names of the stocks in the nasdaq 100.
    /// </summary>
    public enum NasdaqStockNames
    {
        Activision_Blizzard,
        Adobe,
        Advanced_Micro_Devices,
        Alexion_Pharmaceuticals,
        Align_Technology,
        Alphabet,
        Amazon,
        American_Airlines_Group,
        Amgen,
        Analog_Devices,
        Apple,
        Applied_Materials,
        ASML_Holding,
        Autodesk,
        Automatic_Data_Processing,
        Baidu,
        Biogen,
        BioMarin_Pharmaceutical,
        Booking_Holdings,
        Broadcom,
        Cadence_Design_Systems,
        Cerner_Corporation,
        Charter_Communications,
        Check_Point_Software_Technologies,
        Cintas_Corporation,
        Cisco_Systems,
        Citrix_Systems,
        Cognizant_Technology_Solutions_Corporation,
        Comcast_Corporation,
        Costco_Wholesale_Corporation,
        CSX_Corporation,
        Dollar_Tree,
        eBay,
        Electronic_Arts,
        Exelon_Corporation,
        Expedia_Group,
        Facebook,
        Fastenal_Company,
        Fiserv,
        Fox_Corporation,
        Gilead_Sciences,
        Hasbro,
        Henry_Schein,
        IDEXX_Laboratories,
        Illumina,
        Incyte_Corporation,
        Intel_Corporation,
        Intuit,
        Intuitive_Surgical,
        JB_Hunt_Transport_Services,
        JD,
        KLA_Corporation,
        Kraft_Heinz,
        Lam_Research,
        Liberty_Global,
        Lululemon_athletica,
        Marriott_International,
        Maxim_Integrated_Products,
        MercadoLibre,
        Microchip_Technology,
        Micron_Technology,
        Microsoft_Corporation,
        Mondelēz_International,
        Monster_Beverage_Corporation,
        Mylan_NV,
        NetApp,
        NetEase,
        Netflix,
        NVIDIA_Corporation,
        NXP_Semiconductors_NV,
        OReilly_Automotive,
        PACCAR,
        Paychex,
        PayPal_Holdings,
        PepsiCo,
        QUALCOMM_Incorporated,
        Regeneron_Pharmaceuticals,
        Ross_Stores,
        Sirius_XM_Radio,
        Skyworks_Solutions,
        Starbucks_Corporation,
        Synopsys,
        T_Mobile_US,
        Take_Two_Interactive,
        Tesla,
        Texas_Instruments,
        Ulta_Beauty,
        United_Airlines_Holdings,
        VeriSign,
        Verisk_Analytics,
        Vertex_Pharmaceuticals,
        Walgreen_Boots_Alliance,
        Workday,
        Western_Digital,
        Willis_Towers_Watson,
        Wynn_Resorts,
        Xcel_Energy,
        Xilinx
    }
}
