using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GraphProject
{
    /// <summary>
    /// This enum contains all the tickers of the nasdaq 100 stocks.
    /// </summary>
    public enum NasdaqStockTickers
    {
        ATVI,
        ADBE,
        AMD,
        ALXN,
        ALGN,
        GOOG,
        AMZN,
        AAL,
        AMGN,
        ADI,
        AAPL,
        AMAT,
        ASML,
        ADSK,
        ADP,
        BIDU,
        BIIB,
        BMRN,
        BKNG,
        AVGO,
        CDNS,
        CERN,
        CHTR,
        CHKP,
        CTAS,
        CSCO,
        CTXS,
        CTSH,
        CMCSA,
        COST,
        CSX,
        DLTR,
        EBAY,
        EA,
        EXC,
        EXPE,
        FB,
        FAST,
        FISV,
        FOX,
        GILD,
        HAS,
        HSIC,
        IDXX,
        ILMN,
        INCY,
        INTC,
        INTU,
        ISRG,
        JBHT,
        JD,
        KLAC,
        KHC,
        LRCX,
        LBTYK,
        LULU,
        MAR,
        MXIM,
        MELI,
        MCHP,
        MU,
        MSFT,
        MDLZ,
        MNST,
        MYL,
        NTAP,
        NTES,
        NFLX,
        NVDA,
        NXPI,
        ORLY,
        PCAR,
        PAYX,
        PYPL,
        PEP,
        QCOM,
        REGN,
        ROST,
        SIRI,
        SWKS,
        SBUX,
        SNPS,
        TMUS,
        TTWO,
        TSLA,
        TXN,
        ULTA,
        UAL,
        VRSN,
        VRSK,
        VRTX,
        WBA,
        WDAY,
        WDC,
        WLTW,
        WYNN,
        XEL,
        XLNX
    }
}
